config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resources :restaurants

  root 'static#home'
  get '/sign-in' => 'sessions#new'
  delete '/sign-out' => 'sessions#destroy'
  get '/about' => 'static#about'
  get '/cat_pictures(/:number_of_cats)' => 'static#cats', as: :cat_pictures

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  validates_presence_of :name, :address
  validates_numericality_of :rating, :greater_than => 0, :less_than => 6, message: "needs to be a number between 1 and 5", allow_blank: true


  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
  end




end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

private

  def current_user
    User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  def user_signed_in?
    !!current_user
  end
  helper_method :user_signed_in?

  def only_allow_signed_in_users
    unless user_signed_in?
      redirect_to sign_in_url, notice: 'You must sign in to access this part of the app.'
    end
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  before_action :only_allow_signed_in_users, except: [:index, :show]
  # GET /restaurants
  # GET /restaurants.json


  def index
    @restaurants = Restaurant.search(params[:search]).paginate(:page => params[:page], :per_page => 5)
  end



  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end


  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :is_open, :rating)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged in!'
    else
      flash.alert = 'Invalid email/password combination. Please try again.'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Successfully signed out!'
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def about
  end

  def cats
    @cats = CatAPI.new.get_images(results_per_page:params[:number_of_cats] || 1)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
  def current_date_and_time
    Time.now.strftime('%B %-d, %Y at %-l:%M%P')
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Proj10</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |type, message| %>
  <div class="<%= type %>">
    <p><%= message %></p>
  </div>
<% end %>
<%= yield %>
<ul>
  <% if user_signed_in? %>
    <li>Signed in in as <%= current_user.email %></li>
    <li><%= link_to "Sign Out", sign_out_path, method: :delete %></li>
  <% else %>
    <li><%= link_to "Sign In", sign_in_path %></li>
  <% end %>
  <li><%= link_to 'Home', root_path %></li>
  <li><%= link_to 'About', about_path %></li>
  <li><%= link_to 'Cat Pictures', cat_pictures_path %></li>
  <li><%= link_to 'Restaurants', restaurants_path %></li>
</ul>
<%= current_date_and_time %>
</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :is_open %><br>
    <%= f.check_box :is_open %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Restaurants</h1>

<%= will_paginate @restaurants %>


<%= form_tag restaurants_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Is open</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.is_open %></td>
        <td><%= restaurant.rating %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <% if user_signed_in? %>
          <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
          <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<% if user_signed_in? %>
  <%= link_to 'New Restaurant', new_restaurant_path %>
<% end %>
<br>
<h2>Number of restraurants rated 1-5</h2>
<div class="chart">
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js"></script>
<script>
var data = [<%= Restaurant.where(rating:1).count %>,<%= Restaurant.where(rating:2).count %>,
<%= Restaurant.where(rating:3).count %>,<%= Restaurant.where(rating:4).count %>, <%= Restaurant.where(rating:5).count %>];
console.log(data)
d3.select(".chart")
  .selectAll("div")
    .data(data)
  .enter().append("div")
    .style("width", function(d) { return 10 * d + "px"; })
    .text(function(d) { return d; });
</script>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Is open:</strong>
  <%= @restaurant.is_open %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @restaurant.rating %>
</p>
<% if user_signed_in? %>
  <%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<% end %>
<%= link_to 'Back', restaurants_path %>